import { useEffect, useState } from "react";

import Balances from "@/components/Balances";
import ConnectWallet from "@/components/ConnectWallet";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useIsMounted } from "@/hooks/isMounted";

export default function Home() {
  const isMounted = useIsMounted();
  if (!isMounted) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <ConnectWallet />
          <Balances />
        </div>
      </main>
    </>
  );
}
